const TITLE = "How H S Detectives is revolutionizing private investigation in Mumbai with law enforcement expertise";

export const newPublications = [
  { source: "Karnataka News Network", audience: 50236, url: "https://karnatakanewsnetwork.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Buzz Center", audience: 12434, url: "https://buzzcenter.co/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Wire News", audience: 12434, url: "https://indiawirenews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Kerala News Journal", audience: 12434, url: "https://keralanewsjournal.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Indian Link", audience: 12434, url: "https://newsindianlink.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India News Connect", audience: 12434, url: "https://indianewsconnect.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Rajasthan News Time", audience: 12434, url: "https://rajasthannewstime.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Insightful News", audience: 12434, url: "https://insightfulnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Press Buzz", audience: 12327, url: "https://indiapressbuzz.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Headline", audience: 12327, url: "https://newsindiaheadline.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Press Dispatch", audience: 12327, url: "https://indiapressdispatch.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Madhya Pradesh News Tribune", audience: 12327, url: "https://madhyapradeshnewstribune.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Economic India", audience: 12327, url: "https://newseconomicindia.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Daily Street Journal", audience: 12327, url: "https://dailystreetjournal.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Headline News", audience: 12327, url: "https://indianheadlinenews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Maharashtra NewsFlash", audience: 12236, url: "https://maharashtranewsflash.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The Indian Post Online", audience: 12236, url: "https://theindianpostonline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Flash News", audience: 12236, url: "https://indiaflashnews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India", audience: 12236, url: "https://newsindias.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Jharkhand News Hub", audience: 12236, url: "https://jharkhandnewshub.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Forbes News", audience: 12236, url: "https://indiaforbesnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The India Brief", audience: 12236, url: "https://theindiabrief.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Traveller News India", audience: 12058, url: "https://travllernewsindia.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Network", audience: 12058, url: "https://newsindianetwork.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Jharkhand India News Agency", audience: 12058, url: "https://jharkhandindianewsagency.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India News Break", audience: 12058, url: "https://indianewsbreak.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Global Live", audience: 12058, url: "https://indiagloballive.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Gossip Today", audience: 12058, url: "https://gossiptoday24.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Manipur News World", audience: 12058, url: "https://manipurnewsworld.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Indian Update", audience: 11790, url: "https://newsindianupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Newz Today 24", audience: 11790, url: "https://newztoday24.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Mizoram News Pulse", audience: 11790, url: "https://mizoramnewspulse.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Today Daily", audience: 11790, url: "https://indiatodaydaily.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Rapid Report", audience: 11790, url: "https://rapidreport.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The Hindustan Express", audience: 11790, url: "https://thehindustanexpress.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Briefings", audience: 11790, url: "https://indiabriefings.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Bulletin News", audience: 11715, url: "https://indiabulletinnews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Village Voice News", audience: 11715, url: "https://villagevoicenews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Odisha News Voice", audience: 11715, url: "https://odishanewsvoice.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Mizoram News Voice", audience: 11715, url: "https://mizoramnewsvoice.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Report World", audience: 11715, url: "https://reportworld.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The Quick Update", audience: 11715, url: "https://thequickupdate.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Latest News Feed", audience: 11715, url: "https://indialatestnewsfeed.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Times Of India Daily", audience: 11715, url: "https://timesofindiadaily.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian News Daily Update", audience: 11715, url: "https://indiannewsdailyupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Rajasthan Headlines", audience: 11710, url: "https://rajasthanheadlines.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Express Newsfeed", audience: 11710, url: "https://indianexpressnewsfeed.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Weekly News Report", audience: 11710, url: "https://weeklynewsreport.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Globalnews", audience: 11710, url: "https://indiaglobalnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Live News", audience: 11710, url: "https://indialivenews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The News India Now", audience: 11710, url: "https://thenewsindianow.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian News Views", audience: 11710, url: "https://indiannewsviews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian World News", audience: 11448, url: "https://indianworldnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Brief Buzz", audience: 11448, url: "https://briefbuzz.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Punjab News Network", audience: 11448, url: "https://punjabnewsnetwork.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Connectivity", audience: 11448, url: "https://newsindiaconnectivity.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Wire Channel", audience: 11448, url: "https://indiawirechannel.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India 24x7 News", audience: 11448, url: "https://india24x7news.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Eagle India", audience: 11448, url: "https://newseagleindia.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India News Portal", audience: 11443, url: "https://indianewsportal.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Scroll India News", audience: 11443, url: "https://scrollindianews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Reporter Live", audience: 11443, url: "https://indiareporterlive.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Story Line", audience: 11443, url: "https://indiastoryline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Live New Update", audience: 11443, url: "https://indialivenewsupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "State Newz", audience: 11443, url: "https://statenewz.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Today Newsflash", audience: 11443, url: "https://indiatodaynewsflash.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Reach News", audience: 11443, url: "https://reachnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Express News", audience: 11443, url: "https://indianexpressnews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Nagaland News Watch", audience: 11443, url: "https://nagalandnewswatch.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Latest News Update", audience: 11443, url: "https://indialatestnewsupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Press Connect", audience: 11443, url: "https://indianpressconnect.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Business Line Print", audience: 11443, url: "https://businesslineprint.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Meghalaya News Daily", audience: 11443, url: "https://meghalayanewsdaily.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Indian Pulse", audience: 11118, url: "https://newsindianpulse.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Chronicle Today News", audience: 11118, url: "https://chronicletodaynews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Buzz Times", audience: 11118, url: "https://indiabuzztimes.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The Daily Glimpse", audience: 11118, url: "https://thedailyglimpse.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Today Headline", audience: 11118, url: "https://indiatodayheadlines.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Mirror", audience: 11118, url: "https://newsmirror.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Point", audience: 11118, url: "https://newsindiapoint.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Punjab News Update", audience: 11118, url: "https://panjabnewsupdate.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Tribune Times", audience: 11118, url: "https://indiatribunetimes.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Mizoram News Buzz", audience: 11118, url: "https://mizoramnewsbuzz.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Standard News Wire", audience: 11118, url: "https://standardnewswire.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Odisha News Hour", audience: 11118, url: "https://odishanewshour.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian News Update", audience: 11118, url: "https://indiannewsupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Daily India Updates", audience: 11118, url: "https://dailyindiaupdates.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The Indian Post", audience: 10929, url: "https://theindianpost.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Indian Bulletin", audience: 10929, url: "https://newsindianbulletin.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Story India", audience: 10929, url: "https://stroyindia.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Top Icsarena", audience: 10929, url: "https://topicsarena.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Report India", audience: 10929, url: "https://reportindia.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Brief Update", audience: 10929, url: "https://indiabriefupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Nagaland News 24x7", audience: 10929, url: "https://nagalandnews24x7.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Globe Today", audience: 10929, url: "https://indiaglobetoday.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "District Daily News", audience: 10929, url: "https://districtdailynews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The Report Net", audience: 10929, url: "https://thereportnet.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Bihar News Watch", audience: 10929, url: "https://biharnewswatch.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Career Week", audience: 10929, url: "https://indiacareerweek.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Live News Feed", audience: 10929, url: "https://indialivenewsfeed.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Indian Line", audience: 10929, url: "https://newsindianline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Focus News", audience: 10929, url: "https://indianfocusnews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Hoist", audience: 10929, url: "https://hoist.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Latest News Himachal", audience: 10890, url: "https://latestnewshimachal.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Press Coverage", audience: 10890, url: "https://indianpresscoverage.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India World News", audience: 10890, url: "https://indiaworldnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Report Today", audience: 10890, url: "https://reporttoday.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Headline Buzz", audience: 10890, url: "https://indianheadlinebuzz.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Sikkim News Update", audience: 10890, url: "https://sikkimnewsupdate.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Daily Gossip Online", audience: 10890, url: "https://dailygossiponline.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Post Daily", audience: 10890, url: "https://indiapostdaily.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Tripura News Central", audience: 10890, url: "https://tripuranewscentral.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian For Media", audience: 10890, url: "https://indiainformedia.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "My News Today", audience: 10890, url: "https://mynewstoday24.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Times", audience: 10890, url: "https://newsindiatimes.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Global News", audience: 10890, url: "https://indiaglobalnews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The India Talks", audience: 10890, url: "https://theindiatalks.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Pulse Media", audience: 10678, url: "https://indianpulsemedia.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Latest News Karnataka", audience: 10678, url: "https://latestnewskarnataka.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Web", audience: 10678, url: "https://newsindiaweb.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Flashnewsfeed", audience: 10678, url: "https://indiaflashnewsfeed.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Tamilnadu News Update", audience: 10678, url: "https://tamilnadunewsupdate.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Sandwich", audience: 10678, url: "https://sandwich.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Latest News", audience: 10678, url: "https://indialatestnews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian News Channel", audience: 10678, url: "https://indiannewschannel.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Now Report", audience: 10678, url: "https://nowreport.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Andhra News Digest", audience: 10678, url: "https://andhranewsdigest.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Wire Media", audience: 10678, url: "https://indiawiremedia.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The Report World", audience: 10678, url: "https://thereportworld.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Watch Daily", audience: 10678, url: "https://indiawatchdaily.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Daily Press", audience: 10678, url: "https://indiandailypress.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Goa New Time", audience: 10473, url: "https://goanewstime.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "State News Today", audience: 10473, url: "https://statenewstoday.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Today Times", audience: 10473, url: "https://indiatodaytimes.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Today Live Update", audience: 10473, url: "https://indiatodayliveupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Today Pro", audience: 10473, url: "https://newstodaypro.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The India Watch", audience: 10473, url: "https://theindiawatch.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Press Coverage", audience: 10473, url: "https://indiapresscoverage.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Discover Weekly", audience: 10473, url: "https://discoverweekly.co/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Telangana News Spot", audience: 10473, url: "https://telangananewsspot.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Media Minds", audience: 10473, url: "https://mediasminds.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Daily News India Online", audience: 10473, url: "https://dailynewsindiaonline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Chhattisgarh NewsLine", audience: 10473, url: "https://chhattisgarhnewsline.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Times News", audience: 10473, url: "https://indiatimesnews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Express Update", audience: 10473, url: "https://indianexpressupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Patrolling Wire News", audience: 10278, url: "https://patrollingwirenews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Live News Today", audience: 10278, url: "https://indialivenewstoday.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Buzz Channel", audience: 10278, url: "https://indiabuzzchannel.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Today Updates", audience: 10278, url: "https://indiatodayupdates.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Tripura News Point", audience: 10278, url: "https://tripuranewspoint.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Wires", audience: 10278, url: "https://newswires.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Standard Today News", audience: 10278, url: "https://standardtodaynews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Delhi News Daily", audience: 10278, url: "https://delhinewsdaily.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Express Times News", audience: 10278, url: "https://expresstimesnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Press Wire", audience: 10278, url: "https://indianpresswire.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India State News", audience: 10278, url: "https://indiastatenews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Live", audience: 10278, url: "https://newsindialive.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Talks", audience: 10278, url: "https://newsindiatalks.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Times Online", audience: 10278, url: "https://indiatimesonline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Haryana News Time", audience: 10278, url: "https://haryananewstime.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Himachal Pradesh News Flash", audience: 10247, url: "https://himachalpradeshnewsflash.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Current Update", audience: 10247, url: "https://indiacurrentupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India News Nation", audience: 10247, url: "https://indianewsnation.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Pulse Update", audience: 10247, url: "https://indiapulseupdate.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Quick News Now", audience: 10247, url: "https://quicknewsnow.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Former", audience: 10247, url: "https://indiainformer.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Viral Newsnow", audience: 10247, url: "https://indiaviralnewsnow.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Breaking News Line", audience: 10247, url: "https://indiabreakingnewsline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Buzz Feednews", audience: 10247, url: "https://indiabuzzfeednews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Current Affairs", audience: 10247, url: "https://indiacurrentaffairs.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian Express Daily", audience: 10247, url: "https://indianexpressdaily.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The News Net", audience: 10247, url: "https://thenewsnet.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Gujarat Watch", audience: 10247, url: "https://gujaratwatch.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Post Times News", audience: 10247, url: "https://posttimenews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Rabale", audience: 10247, url: "https://rabale.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Watch Live", audience: 10104, url: "https://indiawatchlive.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Goa News Online", audience: 10104, url: "https://goanewsonline.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indian News Beat", audience: 10104, url: "https://indianNewsBeat.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Buzzing Info", audience: 10104, url: "https://buzzinginfo.com/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Jammu and Kashmir News Report", audience: 10104, url: "https://jammuandkashmirnewsreport.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Haryana News Line", audience: 10104, url: "https://haryananewsline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Bulletin Live", audience: 10104, url: "https://indiabulletinlive.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Nagpur Project News", audience: 10104, url: "https://nagpurprojectnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Daily Indiane", audience: 10104, url: "https://dailyindiane.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Report News", audience: 10104, url: "https://reportnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India News Junction", audience: 10104, url: "https://indianewsjunction.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Today99", audience: 10104, url: "https://newstoday99.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Press Journal", audience: 10104, url: "https://indiapressjournal.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Flash Bulletin", audience: 10104, url: "https://indiaflashbulletin.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India News Wire", audience: 10060, url: "https://indianewswire.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News India Connect", audience: 10060, url: "https://newsindiaconnect.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "The India Times Online", audience: 10060, url: "https://theindiatimesonline.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Latest News Today", audience: 10060, url: "https://latestnewstoday.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Himachal News Report", audience: 10060, url: "https://himachalnewsreport.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Wave India", audience: 10060, url: "https://newswaveindia.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Mirror News", audience: 10060, url: "https://indiamirrornews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Tech Times News", audience: 10060, url: "https://techtimesnews.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "New India 24x7", audience: 10020, url: "https://newsindia24x7.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Karnataka News Room", audience: 10020, url: "https://karnatakanewsroom.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "News Pulse India", audience: 10020, url: "https://newspulseindia.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Indsider India Times", audience: 10020, url: "https://insiderindiatimes.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Buzz News", audience: 10020, url: "https://indiabuzznews.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Trend Stellers", audience: 10020, url: "https://trendstellers.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Vibes Media", audience: 10020, url: "https://indiavibesmedia.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "India Breaking Buzz", audience: 8632, url: "https://indiabreakingbuzz.co.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Uttarakhand News Wire", audience: 1090, url: "https://uttarakhandnewswire.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
  { source: "Maharashtra Portal", audience: 1070, url: "https://maharastraportal.in/how-h-s-detectives-is-revolutionizing-private-investigation-in-mumbai-with-law-enforcement-expertise/" },
].map((p) => ({ ...p, title: TITLE }));
