import PageTransition from "@/components/ui/PageTransition";

export const metadata = {
  title: "Ethics & Legal Standards | Private Investigation Mumbai | H S Detectives",
  description:
    "Explore our ethical framework and legal compliance. Led by a retired DCP, H S Detectives Mumbai ensures all investigations are handled with the highest integrity and IPC alignment.",
  keywords: "Private Detective Ethics, Legal Compliance Investigation, Investigation Law India, Ethical Detective Mumbai",
};


const ethicsSections = [
  {
    title: "1. The H S Detectives Standard: Legal Compliance",
    content: "We do not operate outside the law. Every investigation conducted by H S Detectives Agency Mumbai is strictly aligned with the Indian Penal Code (IPC) and the Information Technology Act (2000).",
    points: [
      {
        label: "Admissible Evidence",
        text: "We gather intelligence through professional surveillance and public-domain research so our findings can serve as corroborative evidence in matrimonial or civil courts."
      },
      {
        label: "No Illegal Interception",
        text: "H S Detectives Agency Mumbai strictly prohibits illegal phone tapping or hacking. We rely on sophisticated OSINT (Open Source Intelligence) and expert field-work."
      }
    ]
  },
  {
    title: "2. Our \"Red Lines\" (Strict Non-Negotiables)",
    content: "To protect our clients and our professional standing, H S Detectives Agency Mumbai maintains clear boundaries. We DO NOT engage in:",
    points: [
      {
        label: "Unauthorized Digital Access",
        text: "We do not hack into private social media, emails, or password-protected bank accounts."
      },
      {
        label: "Physical Trespassing",
        text: "We do not enter private residences or restricted corporate zones without legal standing."
      },
      {
        label: "Fabricated Evidence",
        text: "We do not \"set up\" or \"provoke\" subjects. We report only factual, observed truths."
      }
    ]
  },
  {
    title: "3. Absolute Confidentiality & Data Security",
    content: "In the investigative world, discretion is our currency. H S Detectives Agency Mumbai ensures:",
    points: [
      {
        label: "The Vault Protocol",
        text: "All case files, photographs, and video evidence are stored on highly encrypted local servers."
      },
      {
        label: "Data Destruction Policy",
        text: "Once a case is concluded and the final report is delivered, all sensitive raw field data is purged from our systems to ensure it can never be misused."
      },
      {
        label: "Complete Anonymity",
        text: "We never disclose a client's identity to third parties, ensuring total peace of mind for high-profile individuals and corporations."
      }
    ]
  },
  {
    title: "4. Technical Integrity in TSCM & Bug Sweeping",
    content: "As a premier provider of Technical Surveillance Countermeasures (TSCM) in India, H S Detectives Agency Mumbai utilizes USA and Israel-trained experts. We use industrial-grade equipment to provide honest, technical audits of your security—never exaggerating threats to upsell services."
  },
  {
    title: "5. Accountability & Leadership",
    content: "What defines H S Detectives Agency Mumbai is Accountability. Every report generated by our team is vetted for accuracy and ethical alignment by our senior leadership. When you hire us, you are hiring the rigor and transparency of a high-level police inquiry."
  }
];

export default function EthicsPage() {
  return (
    <PageTransition>
      <main className="min-h-screen bg-linear-to-b from-neutral-950 via-neutral-900 to-neutral-950 text-foreground">
        <section className="container mx-auto px-6 lg:px-12 py-24 lg:py-28">
          <div className="max-w-5xl rounded-2xl border border-white/20 bg-white/90 p-8 md:p-10 shadow-[0_20px_60px_rgba(0,0,0,0.35)] mb-12">
            <h1 className="font-playfair text-4xl md:text-5xl uppercase tracking-wide text-neutral-950">
              Our Ethics & Legal Framework
            </h1>
            <p className="mt-6 font-inter text-base md:text-lg text-neutral-700 leading-relaxed max-w-4xl">
              At <span className="font-bold text-black">H S Detectives Agency Mumbai</span>, we believe that private intelligence must be rooted in public integrity. In a complex urban landscape like Mumbai, the difference between a successful investigation and a legal liability is <span className="text-red-700 italic">Ethics</span>. Under the strategic leadership of a <span className="font-bold text-black">Retired Deputy Commissioner of Police (DCP)</span> from Maharashtra, our agency brings law-enforcement-grade discipline to the private sector.
            </p>
          </div>

          <div className="max-w-5xl space-y-8">
            {ethicsSections.map((section, idx) => (
              <div 
                key={idx}
                className="group relative rounded-2xl border border-white/10 bg-black/40 p-8 md:p-10 backdrop-blur-xl hover:border-white/20 transition-all duration-500"
              >
                <div className="absolute top-0 right-0 p-8 opacity-5">
                   <span className="font-bebas text-8xl text-white">{idx + 1}</span>
                </div>
                
                <h2 className="font-playfair text-2xl md:text-3xl text-amber-100 mb-6 relative z-10">
                  {section.title}
                </h2>
                <div className="font-inter text-neutral-300 text-lg leading-relaxed mb-8 relative z-10">
                  {section.content}
                </div>
                
                {section.points && (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
                    {section.points.map((point, pIdx) => (
                      <div key={pIdx} className="p-6 rounded-xl border border-white/5 bg-white/5 hover:bg-white/10 transition-colors">
                        <h3 className="font-space text-sm tracking-widest uppercase text-red-500 mb-3">
                          {point.label}
                        </h3>
                        <p className="font-inter text-sm text-neutral-400 leading-relaxed">
                          {point.text}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>

          <div className="mt-16 max-w-5xl p-8 rounded-2xl bg-red-950/20 border border-red-500/20">
             <p className="font-playfair text-xl text-white italic text-center">
               "Integrity is doing the right thing, even when no one is watching. In our business, it is the only thing."
             </p>
          </div>
        </section>
      </main>
    </PageTransition>
  );
}
